name: command_manager
description: A command manager.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  english_words: ^4.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  system_tray: ^2.0.3
  window_manager: ^0.5.1
  is_admin:
    git:
      url: https://github.com/xxfttkx/is_admin
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.ico
    - assets/app_icon.png
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
